### ISSUE TITLE
/node_modules/mangol/index.ts is not part of the compilation output.

### ISSUE THREAD

**Issue by tilonet** [fegyi001/mangol#20] opened 2017-12-20 13:52 UTC
Angular: 5.1.1
get this error when run ng serve after following "Use as npm library" 

found this on https://github.com/angular/angular-cli/issues/8284

... have TS files in your node_modules. This really goes against how libraries should be packaged: libraries should never ship their source .ts files.
The reason for this rule is that the TypeScript version your app isn't necessarily the same as the TS version your library uses. Different versions of TS can produce different output, and give different errors for the same input. They don't even support the same language features. So packaging libraries with TS sources will always break someone's project. ...

maybe this is the problem ?!?

angular-cli: 1.4.9 fixed problem

**Comment by fegyi001** [comment] 2017-12-21 08:20
@tilonet Thanks for the comment, you are absolutely right about not packaging TS files.

At the moment Mangol is not packaged properly and this is what raises the issue. I'm currently working on fixing it, but it takes a while since a lot of things have to be changed in order to make it right.

**Comment by fegyi001** [comment] 2017-12-28 14:02
@tilonet I completely refactored the project, now the npm module is created via ng-packagr. Please try the latest version (1.0.0 at the time of writing), hopefully the error will disappear.

Did you succeed?

**Comment by fegyi001** [comment] 2018-02-21 14:50
I close the issue since the problem is eliminated by the huge refactor (ng-packagr)

**Closed as completed by fegyi001** 2018-02-21 14:50 UTC
